print("Calculate Velocity from formula V=S/T")
speed = int(input("input speed : "))
time = int(input("input time : "))
print("===========================")
print("speed : ", speed)
print("time : ", time)
print("velocity : ", speed/time)
print("===========================")
